### ISSUE TITLE
How can I open and see the inspector similar web browser?

### ISSUE THREAD

**Issue by camux** [pyloid/pyloid-react-boilerplate#1]
How can I open and see the inspector similar web browser?

For to see console logs and dom of components

Thanks you

**Comment by aesthetics-of-record** [comment]
Thank you! I have added the documentation for the requested feature. You can check the link below to resolve the issue:
https://docs.pyloid.com/guides/devtools-settings

Also, since several changes have been made, including PylonApp being renamed to Pyloid, I recommend downloading the latest version for use.
